ejemplo_django/urls.py
from . import views
from django.urls import path

app_name = 'ejemplo_django'

urlpatterns = [
    path('',views.index,name='index'),
    path('hola',views.hola,name='hola'),
    path('hastaLuego',views.hastaLuego,name='hastaLuego'),
    path('usuariosInfo',views.usuariosInfo,name='usuariosInfo')
]

miPrimerProyecto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ejemplo_django/',include('ejemplo_django.urls'))
]

ejemplo_django/models.py
from django.db import models

# Create your models here.
class estudiante(models.Model):
    nombre = models.CharField(max_length=128,default='')
    apellido = models.CharField(max_length=128,default='')
    codigo = models.CharField(max_length=128,default='')
    direccion = models.CharField(max_length=128,default='')
    email = models.CharField(max_length=128,default='')

ejemplo_django/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django.http import HttpResponse
from .models import estudiante

# Create your views here.

informacion_usuarios = [['Alexander','Segovia'],['Javier','Hilario'],['Martin','Leiva']]

def index(request):
    return HttpResponse('Mi primera aplicación web')

def hola(request):
    lista_elementos = ['Python','Django','Flask','Javascript','Docker']
    return render(request,'ejemplo_django/hola.html',{
        'lista_elementos':lista_elementos,
        'm2':'Este es un segundo mensaje (2)',
    })

def hastaLuego(request):
    return render(request,'ejemplo_django/hastaLuego.html')

def usuariosInfo(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        apellidoUsuario = request.POST.get('usuarioApellido')
        codigoUsuario = request.POST.get('codigoUsuario')
        direccionUsuario = request.POST.get('direccionUsuario')
        emailUsuario = request.POST.get('emailUsuario')
        informacion_usuarios.append([nombreUsuario,apellidoUsuario])
        estudiante(nombre=nombreUsuario, apellido=direccionUsuario, codigo=codigoUsuario, direccion=direccionUsuario, email=emailUsuario).save()
        return render(request,'ejemplo_django/usuariosInfo.html',{
            'informacion_usuarios':estudiante.objects.all(),
        })
    return render(request,'ejemplo_django/usuariosInfo.html',{
        'informacion_usuarios':estudiante.objects.all(),
    })

ejemplo_django/templates/ejemplo_django/hastaLuego.html
{% extends "ejemplo_django/layout.html" %}

{% block contenido%}
<div>
    <ul>
        <h2>Eso fue todo amigos</h2>
    </ul>
</div>
{% endblock%}

ejemplo_django/templates/ejemplo_django/hola.html
{% extends "ejemplo_django/layout.html" %}

{% block contenido%}
<div>
    <ul>
        {% for elemento in lista_elementos %}
        <li>{{ elemento }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock%}

ejemplo_django/templates/ejemplo_django/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Vista 1</title>
    </head>
    <body>
        <div>
            <a href="">Enlace 1</a>
            <a href="">Enlace 2</a>
            <a href="">Enlace 3</a>
        </div>
        <div>
            <h2>Esta es una página de prueba</h2>
        </div>
        {% block contenido %}
        {% endblock%}
    </body>
</html>

ejemplo_django/templates/ejemplo_django/usuariosInfo.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>
            Lista de Usuarios
        </title>
        <link href="{% static 'ejemplo_django/estilo.css' %}" rel="stylesheet">
        <script src="{% static 'ejemplo_django/codigo_ejemplo.js' %}"></script>
    </head>
    <body>
        <div>
            <h1>Ingresar datos</h1>
        </div>
            <form method="post" action="{% url 'ejemplo_django:usuariosInfo' %}">
            {% csrf_token %}
                <div>
                    <label>Nombre :</label>
                    <input type="text" name="nombreUsuario">
                </div>
                <div>
                    <label>Apellido : </label>
                    <input type="text" name="apellidoUsuario">
                </div>
                <div>
                    <label>Código : </label>
                    <input type="text" name="codigoUsuario">
                </div>
                <div>
                    <label>Dirección : </label>
                    <input type="text" name="direccionUsuario">
                </div>
                <div>
                    <label>email : </label>
                    <input type="text" name="emailUsuario">
                </div>
                <div>
                    <h2>Estos son los uauarios registrados</h2>
                </div>
                <div>
                    <button type="submit">Enviar información</button>
                <div>
            </form>        
            <ul>
                {% for estudiante in informacion_usuarios %}
                <li>Nombre: {{ estudiante.nombre }} Código: {{ estudiante.codigo }} </li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>